/**
 * @packageDocumentation
 * @module api.functional.api.v1.me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";

import type { MeResponse } from "../../../../structures/MeResponse";

/**
 * @operationId v1.me.get
 * @controller MeController.getMe
 * @path GET /api/v1/me
 * @accessor api.functional.api.v1.me.getMe
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getMe(connection: IConnection): Promise<getMe.Output> {
  return PlainFetcher.fetch(connection, {
    ...getMe.METADATA,
    template: getMe.METADATA.path,
    path: getMe.path(),
  });
}
export namespace getMe {
  export type Output = MeResponse;

  export const METADATA = {
    method: "GET",
    path: "/api/v1/me",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/v1/me";
}
