/**
 * @packageDocumentation
 * @module api.functional.api.v1.me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { tags } from "typia";

/**
 * @operationId v1.me.get
 * @controller MeController.getMe
 * @path GET /api/v1/me
 * @accessor api.functional.api.v1.me.getMe
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getMe(connection: IConnection): Promise<getMe.Output> {
  return PlainFetcher.fetch(connection, {
    ...getMe.METADATA,
    template: getMe.METADATA.path,
    path: getMe.path(),
  });
}
export namespace getMe {
  export type Output = {
    user: {
      id: string;
      createdAt: string & tags.Format<"date-time">;
      updatedAt: string & tags.Format<"date-time">;
      email: string;
      emailVerified: boolean;
      name: string;
      image?: null | undefined | string;
    };
    session: {
      id: string;
      createdAt: string & tags.Format<"date-time">;
      updatedAt: string & tags.Format<"date-time">;
      userId: string;
      expiresAt: string & tags.Format<"date-time">;
      token: string;
      ipAddress?: null | undefined | string;
      userAgent?: null | undefined | string;
    };
  };

  export const METADATA = {
    method: "GET",
    path: "/api/v1/me",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/v1/me";
}
