/**
 * @packageDocumentation
 * @module api.functional.api.v1.app.hello
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";

import type { HelloResponse } from "../../../../../structures/HelloResponse";

/**
 * @operationId v1.app.hello
 * @controller AppController.getHello
 * @path GET /api/v1/app/hello
 * @accessor api.functional.api.v1.app.hello.getHello
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getHello(
  connection: IConnection,
): Promise<getHello.Output> {
  return PlainFetcher.fetch(connection, {
    ...getHello.METADATA,
    template: getHello.METADATA.path,
    path: getHello.path(),
  });
}
export namespace getHello {
  export type Output = HelloResponse;

  export const METADATA = {
    method: "GET",
    path: "/api/v1/app/hello",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/v1/app/hello";
}
