/**
 * @packageDocumentation
 * @module api.functional.api.v1.health
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";

import type { HealthCheckResponse } from "../../../../structures/HealthCheckResponse";

/**
 * @operationId v1.health.check
 * @controller HealthController.check
 * @path GET /api/v1/health
 * @accessor api.functional.api.v1.health.check
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function check(connection: IConnection): Promise<check.Output> {
  return PlainFetcher.fetch(connection, {
    ...check.METADATA,
    template: check.METADATA.path,
    path: check.path(),
  });
}
export namespace check {
  export type Output = HealthCheckResponse;

  export const METADATA = {
    method: "GET",
    path: "/api/v1/health",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/v1/health";
}
