/**
 * @packageDocumentation
 * @module api.functional.api.v1.app.demo_error
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";

/**
 * @operationId v1.app.demoError
 * @throws 503
 * @controller AppController.demoError
 * @path GET /api/v1/app/demo-error
 * @accessor api.functional.api.v1.app.demo_error.demoError
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function demoError(connection: IConnection): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...demoError.METADATA,
    template: demoError.METADATA.path,
    path: demoError.path(),
  });
}
export namespace demoError {
  export const METADATA = {
    method: "GET",
    path: "/api/v1/app/demo-error",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/v1/app/demo-error";
}
